alert:
- debug
description: Detects potential lateral movement via dcom
filter:
- query:
    query_string:
      query: (event_id:1 AND process_name:("outlook.exe" OR "excel.exe" OR "winword.exe" OR "powerpnt.exe" OR "mmc.exe") AND process_command_line:*Embedding*)
index: logs-endpoint-winevent-sysmon-*
name: Windows-dcom-lm_0
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any