alert:
- debug
description: Detects potential lateral movement via logon scripts
filter:
- query:
    query_string:
      query: (event_id:13 AND registry_key_path:*Environment* AND registry_key_path:*UserInitMprLogonScript*)
index: logs-endpoint-winevent-sysmon-*
name: Windows-logonscript-lm_0
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any