alert:
- debug
description: Detects process LSASS memory dump using procdump or taskmgr based on
  the CallTrace pointing to dbghelp.dll or dbgcore.dll for win10
filter:
- query:
    query_string:
      query: (event_id:"10" AND target_process_path.keyword:(*\\lsass.exe) AND process_granted_access_orig:0x1fffff AND process_call_trace.keyword:(*dbghelp.dll* OR *dbgcore.dll*))
index: logs-endpoint-winevent-sysmon-*
name: LSASS-Memory-Dump_0
priority: 2
realert:
  minutes: 0
type: any
