alert:
- debug
description: Detects potential use of named pipes by Cobalt Strike agents
filter:
- query:
    query_string:
      query: (pipe_name:"msagent*")
index: logs-endpoint-winevent-sysmon-*
name: Windows-Cobalt-Strike-Named-Pipes_0
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any