alert:
- debug
description: Detects use of winrm over the network
filter:
- query:
    query_string:
      query: (event_id:1 AND process_parent_name:"wsmprovhost.exe")
index: logs-endpoint-winevent-sysmon-*
name: Windows-wsmprovhost-winrm_0
priority: 2
realert:
  minutes: 0
timestamp_field: etl_processed_time
type: any